apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stackstorm-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stackstorm
    spec:
      containers:
      - name: stackstorm
        image: stackstorm/stackstorm:latest
        ports:
        - containerPort: 8080
